done tasks from 3-module
js-tasks-ru/jsbasic-20230302_stonehedgedevel pull request #2
Opened 2023-03-27 16:46 UTC by nosanov

2023-03-27 16:47 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-03-28 12:19 UTC, SinimaWath requested changes

2023-03-28 12:19 UTC, SinimaWath commented on 3-module/1-task/index.js
> +  return names;
Здесь не нужен вложенный forEach, для преобразования массива есть метод map
```javascript
function namify(users) {
  return users.map((user) => user.name);
}
```

2023-03-28 12:19 UTC, SinimaWath commented on 3-module/2-task/index.js
> +  return [...arr].filter(el => (el >= a && el <= b));
Тут нет необходимости в `[...arr]`, так как filter не изменяет исходный массив

2023-03-28 12:19 UTC, SinimaWath commented on 3-module/3-task/index.js
> +  return newStr;
Давай это задачу решим в 3 этапа:
```
str.split('-').map(.....).join('')
```

2023-03-28 12:19 UTC, SinimaWath commented on 3-module/4-task/index.js
> +  return resultString;
Давай это задачу решим в 3 этапа:
```
users.filter().map().join('\n')
```

2023-04-02 20:33 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-04-03 08:51 UTC, SinimaWath approved these changes

2023-04-03 08:52 UTC, merged